services:
  tars-server:
    build:
      context: .
      dockerfile: Dockerfile.development
    restart: unless-stopped
    volumes:
      - ./backend/src/:/app/src
      - ./outputs/:/app/outputs
      - ./temp/:/app/temp
      - ./data/:/app/data
    ports:
      - ${PORT}:${PORT}
    environment:
      TZ: Asia/Tokyo
    env_file:
      - .env